name: Action in workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  action_in_workflow:
    runs-on: ubuntu-latest
    name: Run action in workflow
    steps:
    - uses: actions/checkout@v2
    - name: olm-bundle action
      id: bundle
      uses: ./ # Uses the action in the root directory.
      with:
        manifestsDir: testdata/bundle/manifests
        outputDir: testdata/memcached/0.0.2
        channels: stable,beta
        package: memcached
    - name: Tree output
      run: echo "${{ steps.bundle.outputs.tree }}"
